name: Generous Acupuncture
favicon: null
layout_spectrum: 0.26791
typography_spectrum: 0.6623839852400124
title: Generous Acupuncture
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76234426-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.0625
  rhythmicContrast: 0.052090481389313936
purpose: []
