name: Generous Acupuncture
favicon: null
layout_spectrum: 0.51595
typography_spectrum: 0.75751
title: Generous Acupuncture
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76234426-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0
  lightness: 0.875
  saturation: 0
  rhythmicContrast: 1
purpose: []
