name: Generous Acupuncture
favicon: null
layout_spectrum: 0.1788
typography_spectrum: 0.75751
title: Generous Acupuncture
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76234426-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b3d9ca'
    - '#00213d'
    - '#527f6b'
    - '#ce7c54'
    - '#135b5a'
  brandStrength: 0
  lightness: 0.875
  saturation: 0
  rhythmicContrast: 1
purpose: []
